### PR TITLE
Fix r7rs imports for guile

### PR DESCRIPTION
**Pull request by apteryks**

### CODE REVIEW

**Comment by TaylanUB** [comment]
I think the `(r6rs hashtables)` import is actually in reference to the file `r6rs/hashtables.sld` in this repository. This "shim" library checks for the presence of `(rnrs hashtables)`, uses that if present, and otherwise tries to imitate it on the basis of SRFI 69. This way, it works on a wide variety of systems, even those that don't support R6RS.

However, we seem to be missing `(r6rs enums)` here. It's present in Larceny:

https://github.com/TaylanUB/larceny/blob/master/tools/R6RS/r6rs/enums.body.scm

I'm not sure if there's any R7RS implementation other than Larceny that offers an implementation of `(rnrs enums (6))` under the name `(r6rs enums)` right now, but it's implemented in terms of R7RS-small, so one could just use the implementation linked above.

On the other hand, changing the `(r6rs ...)` imports to `(rnrs ... (6))` will make it only work on systems that support proper R6RS libraries.

For that reason, I think it would be best to just use a different `126.sld` in Guile, and not modify the one in here. Since this is a reference implementation, it should work on the widest possible set of Scheme implementations.

As for why it didn't use `include`: This was probably just because the R6RS implementation doesn't use it (since R6RS doesn't have `include`) so the R7RS implementation didn't either. In other words, no actual reason to avoid `include` in the R7RS implementation.

**Comment by apteryks** [comment]
@TaylanUB I've made the change specific to Guile; now if an implementation errors out compiling forms it doesn't need to expand, it'd still fail.  I'll try testing it one chicken and chibi, which I have easy access to via Guix.

**Comment by apteryks** [comment]
Chicken: don't know how to make it work there, there's no r6rs enums or hashtables libraries, and import bails out on a R6RS-style import: (rnrs enums (6)).  It also seems to lack (scheme base), unless the error is misreported.

Edit: seems you need to add the r7rs library, which is not included in the base  distribution.  It's not available on my system, so I haven't tried.

**Comment by apteryks** [comment]
Chibi also lacks (r6rs ...) modules:

~/src/srfi-126 [env]$ chibi-scheme -I$PWD srfi/126.sld
WARNING: exception inside undefined operator: define-library
ERROR on line 35 of file srfi/126.sld: couldn't find import: (r6rs enums)

**Comment by apteryks** [comment]
```
$ kawa --r7rs -f srfi/126.sld
srfi/126.sld:25:4: unknown library (srfi 27)
srfi/126.sld:35:13: unknown library (r6rs enums)
srfi/126.sld:5:4: 'weakness' exported but never defined
/home/maxim/src/srfi-126/srfi/126.body.scm:62:2: warning - no declaration seen for define-enumeration
/home/maxim/src/srfi-126/srfi/126.body.scm:62:21: warning - no declaration seen for weakness
[...]
```

Conclusion: well, at least it now works in Guile (and larceny?)

**Comment by TaylanUB** [comment]
After some thinking: Let's just do it. This way it works with Guile for sure, *probably* still works with Larceny (not sure if it will complain about invalid import syntax due to the `(6)` in the non-matching cond-expand arm), and testing it on other implementations requires some work to set up those `(r6rs ...)` libraries anyway, so a small modification to the imports shouldn't be a big deal for them.

Perhaps you want to change the comment re. licensing though, as it seems that the "lawful purposes" clause is compatible? (Based on the recent thread on the guile-devel mailing list.)

**Comment by apteryks** [comment]
I've removed the part mentioning the license incompatibility for now, as it may not be a problem as you wrote.

**Comment by TaylanUB** [comment]
@arthurgleckler I think this can be merged.

**Comment by apteryks** [comment]
@arthurgleckler ping :-)  See Taylan's last reply up-thread.

**Comment by arthurgleckler** [comment]
Merged and pushed.

Thanks to everyone, and happy new year.

**Pull request merged**
